# Default values for OpenWhisk.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# zookeeper configurations
zookeeper:
  deploymentName: "zookeeper"
  replicaCount: 1
  restartPolicy: "Always"
  containerName: "zookeeper"
  image: "zookeeper:3.4"
  imagePullPolicy: "IfNotPresent"
  serverPort: 2888
  leaderElectionPort: 3888

# kafka configurations
kafka:
  statefulsetName: "kafka"
  replicaCount: 1
  image: "solsson/kafka:0.11.0.0"
  imagePullPolicy: "IfNotPresent"

# Couchdb configurations
couchdb:
  deploymentName: "couchdb"
  replicaCount: 1  
  imagePullPolicy: "IfNotPresent"
  image: "zhiminwen/ow-couchdb:0.1.0"
  dbPrefix: "ow_"
  persistence:
    enabled: true
    size: 5Gi
    # storageClass:
    accessMode: ReadWriteOnce


# Nginx configurations
nginx:
  secretName: "nginx"
  configmapName: "nginx"
  deploymentName: "nginx"
  replicaCount: 1
  image: "tomxing/openwhisk_nginx"
  imagePullPolicy: "IfNotPresent"
  httpPort: 80
  httpsPort: 443
  httpsAdminPort: 8443
  serviceName: "nginx"

# Controller configurations
controllerReplicaCount: 1 
controllerImagePullPolicy: "IfNotPresent"
controllerImage: "openwhisk/controller" 
controllerInstances: 1
controllerLimitsActionsInvokesConcurrentinsystem: 100
controllerLimitsTriggersFiresPerminute: 100
controllerLimitsActionsSequenceMaxlength: 1000
controllerLimitsActionsInvokesConcurrent: 100
controllerLimitsActionsInvokesConcurrentinsystem: 100

# Invoker configurations
invokerStatefulsetName: "invoker"
invokerReplicasetCount: 1
invokerImagePullPolicy: "IfNotPresent"
invokerImage: "openwhisk/invoker" 
invokerInstances: 1
invokerOptions: ""

activationsTable: "ow_activations"
actionsTable: "ow_whisks"
authsTable: "ow_subjects" # same as the prefix
 
# Global configurations
global:
  zookeeperServiceName: "zookeeper"
  kafkaServiceName: "kafka"
  zookeeperPort: 2181
  kafkaPort: 9092
  couchdbServiceName: "couchdb"
  couchdbPort: 5984
  controllerStatefulsetName: "controller"
  controllerServiceName: "controller"
  controllerPort: 8080
  couchdbUserName: "whisk_admin"
  couchdbPassword: "some_passw0rd"
